---
title: "exp-sim"
author: "Murray S Bennett"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}
options(htmltools.dir.version = FALSE)
options(digits=3)

library(ggplot2)
library(gridExtra)
library(knitr)
knitr::opts_chunk$set(
	echo = TRUE,
	cache = FALSE,
	cache.extra = packageVersion("tufte"),
	comment = "",
	tidy = FALSE
)
knitr::opts_chunk$set(cache=FALSE)
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
knitr::opts_chunk$set(comment="")

library(reshape)
library(rstan)
rstan_options(auto_write=TRUE)
options(mc.cores = parallel::detectCores(logical = FALSE))

library(lemon)

# ggtheme_tufte <- function() {
#   theme(plot.background =
#           element_rect(fill = "#fffff8",
#                        colour = "#fffff8",
#                        size = 0.5,
#                        linetype = "solid"),
#         plot.margin=unit(c(1, 1, 0.5, 0.5), "lines"),
#         panel.background =
#           element_rect(fill = "#fffff8",
#                        colour = "#fffff8",
#                        size = 0.5,
#                        linetype = "solid"),
#         panel.grid.major = element_line(colour = "white", size = 1, linetype="dashed"),
#           # blank(),
#         panel.grid.minor = element_blank(),
#         legend.box.background =
#           element_rect(fill = "#fffff8",
#                        colour = "#fffff8",
#                        linetype = "solid"),
#         axis.ticks = element_blank(),
#         axis.text = element_text(family = "Palatino", size = 16),
#         axis.title.x = element_text(family = "Palatino", size = 20,
#                                     margin = margin(t = 15, r = 0, b = 0, l = 0)),
#         axis.title.y = element_text(family = "Palatino", size = 18,
#                                     margin = margin(t = 0, r = 15, b = 0, l = 0)),
#         strip.background = element_rect(fill = "#fffff8",
#                                         colour = "#fffff8",
#                                         linetype = "solid"),
#         strip.text = element_text(family = "Palatino", size = 16),
#         legend.text = element_text(family = "Palatino", size = 16),
#         legend.title = element_text(family = "Palatino", size = 16,
#                                     margin = margin(b = 5)),
#         legend.background = element_rect(fill = "#fffff8",
#                                         colour = "#fffff8",
#                                         linetype = "solid"),
#         legend.key = element_rect(fill = "#fffff8",
#                                         colour = "#fffff8",
#                                         linetype = "solid")
#   )
# }
printf <- function(msg = "%5.3f", ...) {
  cat(sprintf(msg, ...))
}
```

## Simulate BTL model using experiment design

Random competition generation and BTL model analysis as you will be doing it.

```{r echo=FALSE}

n_players <- 50
n_trials <- 50^2

players <- seq(1, n_players)
sim_col_names <- c("player0", "player1", "winner")
data <- data.frame(matrix(ncol=3, nrow=n_trials, dimnames=list(NULL, sim_col_names)))

get_contests <- function(p_list, trials){
  players <- sample(p_list, trials * 2, replace = T)
  contests <- matrix(players, nrow = trials, byrow = T)
  
  no_mates <- contests[, 1] == contests[, 2]
  while (sum(no_mates > 0)){
    contests[no_mates, 1] <- sample(p_list, sum(no_mates), replace=T)
    no_mates <- contests[, 1] == contests[, 2]
  }
  
  return( contests )
}

inv_logit <- function(u){
  inv_log <- 1 / (1 + exp(-u))
  return ( inv_log )
}

center <- function(u){
  c <- u - sum(u) / length(u)
  return ( c )
}


data[, 1:2] <- get_contests(players, n_trials)

alpha <- center(rnorm(n_players))
log_odds_p1 <- alpha[data$player1] - alpha[data$player0]
win_prob_p1 <- inv_logit(log_odds_p1)

y <- rbinom(n_trials, 1, win_prob_p1)
data$winner <- y
```

```{r, show data, caption="Data printed used `kable`.", render=lemon_print}
head(data)
```
# Maximum likelihood estimates
``` 
{stan output.var="mle_model"}
// this outputs the model to a variable, not a saved file

data {
  int<lower = 0> K;
  int<lower = 0> N;
  int<lower = 1, upper = K> player1[N];
  int<lower = 1, upper = K> player0[N];
  int<lower = 0, upper = 1> y[N];
}
parameters {
  vector[K] alpha; // ability for player n
}
model {
  y ~ bernoulli_logit(alpha[player1] - alpha[player0]);
}
generated quantities {
  int<lower=1, upper=K> ranked[K] = sort_indices_desc(alpha);
}

```

# Bayesian Model
``` 
{stan output.var="bayesian_ind"}
data {
  int<lower = 0> K;
  int<lower = 0> N;
  int<lower = 1, upper = K> player1[N];
  int<lower = 1, upper = K> player0[N];
  int<lower = 0, upper = 1> y[N];
}
parameters {
  vector[K] alpha; // ability for player n
}
model {
  alpha ~ normal(0, 1);
  y ~ bernoulli_logit(alpha[player1] - alpha[player0]);
}
generated quantities {
  int<lower=1, upper=K> ranking[K];       // rank of player ability
  {
    int ranked_index[K] = sort_indices_desc(alpha);
    for (k in 1:K)
      ranking[ranked_index[k]] = k;
  }
}
```

```{r model estimation, message=FALSE}

mle_model_data <- 
  list(K = n_players, N = n_trials, player0 = data$player0, player1 = data$player1, y = data$winner )

mle_model_estimates <- optimizing(mle_model, data=mle_model_data)

individual_posterior <- sampling(bayesian_ind, data = mle_model_data)
print(individual_posterior, "alpha", probs=c(0.05, 0.5, 0.95))

```

# Plot ability MLEs
``` {r}
alpha_star <- mle_model_estimates$par[paste("alpha[", 1:n_players, "]", sep="")]
mle_data <- data.frame(alpha = alpha, alpha_star = alpha_star)

ranked_players <- mle_model_estimates$par[paste("ranked[", 1:n_players, "]",sep="")]

alpha_hat <- rep(NA, n_players)
for (player in 1:n_players)
  alpha_hat[player] <- mean(extract(individual_posterior)$alpha[ , player])

mle_plot <-
  ggplot(mle_data, aes(x = alpha, y = alpha_star)) +
      geom_abline(slope = 1, intercept = 0, color="green", linewidth = 2) +
      geom_point(size = 2) 

bayes_fit_plot <-
  ggplot(data.frame(alpha = alpha, alpha_hat = alpha_hat),
         aes(x = alpha, y = alpha_hat)) +
      geom_abline(slope = 1, intercept = 0, color="green", size = 2) +
      geom_point(size = 2)

mle_plot
bayes_fit_plot

```