import os
from pathlib import Path


# Melanoma identification directory
HOME_PATH = Path(__file__).resolve().parent.parent

PATHS = dict(
    home=HOME_PATH,
    images=HOME_PATH / "images" / "resized",
    masks=HOME_PATH / "images" / "masks",
    segmented=HOME_PATH / "images" / "segmented",
    cv=HOME_PATH / "pwc" / "cv",
    estimates=HOME_PATH / "pwc" / "data" / "estimates",
    raw_data = HOME_PATH / "pwc" / "data" / "raw",
    clean_data=HOME_PATH / "pwc" / "data" / "cleaned",
    figures = HOME_PATH / "pwc" / "figures",
    svm_models=HOME_PATH / "pwc" / "models",

)

FILES = dict(
    # required and checked below
    metadata=HOME_PATH / "images" / "ISIC-database" / "metadata.csv",
    malignant_ids = PATHS['cv'] / "01_feature-analysis" / "malignant_ids.txt",
    # required, but generated by scripts, so not checked
    cv_shape=PATHS['cv'] / "01_feature-analysis" / f"cv_shape.txt",
    cv_colour=PATHS['cv'] / "01_feature-analysis" / f"cv_colour.txt",
    cv_data=PATHS['estimates'] / "cv-data.csv",
    btl_data=PATHS['estimates'] / "btl_data.csv",
    btl_cv = PATHS['estimates'] / "btl_cv_data.csv"
)


for req_directory_paths in ['masks', 'segmented', 'estimates', 'raw_data', 'clean_data', 'figures', 'svm_models']:
    path = PATHS[req_directory_paths]
    try:
        path.mkdir(parents=True, exist_ok=True)
    except Exception as e:
        print(f"Error creating {path.name}: {e}")
    
for req_file_paths in ['metadata', 'malignant_ids']:
    file = FILES[req_file_paths]
    if not file.exists():
        print(f"I can't find the metadata file: {file}. This is an unhelpful message, but we will need it. [1] Check that you have the file somewhere, or [2] check that it's in the correct location, otherwise [3] contact Murray and disparage him for this oversight.")

if not PATHS['images'].is_dir():
    print(f"I can't find the images directory: {PATHS['images']}. You will definitely need that one. Are you in the correct directory? If yes and it still fails, contact Murray.")

